{"name": "test_control_account_a1_error_7", "status": "passed", "description": "添加风控账户失败得用例", "attachments": [{"name": "log", "source": "103870b6-e4db-44eb-9d0f-6a017a2104d9-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "274df402-653b-4c46-b8f5-90f1196ea97b-attachment.txt", "type": "text/plain"}], "start": 1617349270846, "stop": 1617349272084, "uuid": "af4f93ea-3ca1-45c3-876e-af3216e03869", "historyId": "a50249825e096484e7fe7c50111d2717", "testCaseId": "a212c7ade000502e8abdbd57514be01b", "fullName": "tests.test_a4_Riskcontrolaccount.TestAddRiskControlAccount#test_control_account_a1_error_7", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_a4_Riskcontrolaccount"}, {"name": "subSuite", "value": "TestAddRiskControlAccount"}, {"name": "host", "value": "DESKTOP-U13POE8"}, {"name": "thread", "value": "6480-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_a4_Riskcontrolaccount"}]}