{"name": "test_control_account_a1_error_1", "status": "passed", "description": "添加风控账户失败得用例", "attachments": [{"name": "log", "source": "693b549e-3621-42b2-b690-65e69b454b9c-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "24c6bfa9-2c0f-4d6d-91ea-4fac3eee92b0-attachment.txt", "type": "text/plain"}], "start": 1617349263366, "stop": 1617349264659, "uuid": "e11017c9-9d58-4082-8bcc-55b7861c2b09", "historyId": "c7fe94f0e5f6690008daecfac1beea40", "testCaseId": "d2913c10c37f1ac7602760ad79f54fbc", "fullName": "tests.test_a4_Riskcontrolaccount.TestAddRiskControlAccount#test_control_account_a1_error_1", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_a4_Riskcontrolaccount"}, {"name": "subSuite", "value": "TestAddRiskControlAccount"}, {"name": "host", "value": "DESKTOP-U13POE8"}, {"name": "thread", "value": "6480-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_a4_Riskcontrolaccount"}]}