{"name": "test_control_account_a1_error_2", "status": "passed", "description": "添加风控账户失败得用例", "attachments": [{"name": "log", "source": "1289ee46-4aa4-47c2-a562-280f546d97c3-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "94c6a68d-41e6-4b8e-97d7-5345ed86a6ee-attachment.txt", "type": "text/plain"}], "start": 1617349264661, "stop": 1617349265920, "uuid": "382d3df4-fc3f-47ce-955d-da248320785b", "historyId": "7c7674f6bd9f657ae8b2f7edbcb40aac", "testCaseId": "fc4361de77ce43a958c56ff847eede93", "fullName": "tests.test_a4_Riskcontrolaccount.TestAddRiskControlAccount#test_control_account_a1_error_2", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_a4_Riskcontrolaccount"}, {"name": "subSuite", "value": "TestAddRiskControlAccount"}, {"name": "host", "value": "DESKTOP-U13POE8"}, {"name": "thread", "value": "6480-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_a4_Riskcontrolaccount"}]}