{"name": "test_control_account_a1_error_4", "status": "passed", "description": "添加风控账户失败得用例", "attachments": [{"name": "log", "source": "b9e5ab20-49e1-4260-a64e-736d330ebdc9-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "3f6adbb0-7723-4cb4-bb7c-aaf16a6a07ae-attachment.txt", "type": "text/plain"}], "start": 1617349267146, "stop": 1617349268353, "uuid": "946249a1-91e7-4a96-902b-fc521e579d76", "historyId": "7952741890cad4c5ade4e3623f90eff8", "testCaseId": "0c960008b147d2ad0493a59156cace88", "fullName": "tests.test_a4_Riskcontrolaccount.TestAddRiskControlAccount#test_control_account_a1_error_4", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_a4_Riskcontrolaccount"}, {"name": "subSuite", "value": "TestAddRiskControlAccount"}, {"name": "host", "value": "DESKTOP-U13POE8"}, {"name": "thread", "value": "6480-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_a4_Riskcontrolaccount"}]}