{"name": "test_control_account_a1_error_5", "status": "passed", "description": "添加风控账户失败得用例", "attachments": [{"name": "log", "source": "41a35361-dc07-4f98-8341-6e2123e0497c-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "07f00b15-c44a-4293-a2fb-44f1f928b620-attachment.txt", "type": "text/plain"}], "start": 1617349268355, "stop": 1617349269592, "uuid": "90c4cf31-172c-471d-a293-5613ef04264e", "historyId": "5434cf4be2bc615358bc686fe1ea403a", "testCaseId": "04f6e68b885e217ec7f3c79e3bcb150f", "fullName": "tests.test_a4_Riskcontrolaccount.TestAddRiskControlAccount#test_control_account_a1_error_5", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_a4_Riskcontrolaccount"}, {"name": "subSuite", "value": "TestAddRiskControlAccount"}, {"name": "host", "value": "DESKTOP-U13POE8"}, {"name": "thread", "value": "6480-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_a4_Riskcontrolaccount"}]}