{"name": "test_control_account_a1_error_6", "status": "passed", "description": "添加风控账户失败得用例", "attachments": [{"name": "log", "source": "98019568-eeba-4785-8158-ef854291fd6e-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "11d2e9e1-f62a-45fb-a45a-b72ce58f49d0-attachment.txt", "type": "text/plain"}], "start": 1617349269594, "stop": 1617349270844, "uuid": "e35d47e6-56bf-4990-aae3-7b83f1456039", "historyId": "1c9f38402801a39edcc19360e4a90e95", "testCaseId": "ac6f6a34f7a1706b284a9e8bde1579c1", "fullName": "tests.test_a4_Riskcontrolaccount.TestAddRiskControlAccount#test_control_account_a1_error_6", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_a4_Riskcontrolaccount"}, {"name": "subSuite", "value": "TestAddRiskControlAccount"}, {"name": "host", "value": "DESKTOP-U13POE8"}, {"name": "thread", "value": "6480-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_a4_Riskcontrolaccount"}]}