{"name": "test_control_account_a1_error_3", "status": "passed", "description": "添加风控账户失败得用例", "attachments": [{"name": "log", "source": "53e6b8fe-f035-47db-869b-2a7002172e4c-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "52dfba3e-005f-45c3-ba97-229ce4ff2446-attachment.txt", "type": "text/plain"}], "start": 1617349265922, "stop": 1617349267144, "uuid": "0869cd13-094b-4a58-b4b2-87f9911df633", "historyId": "f835095cd920d257e8c03e7139db21a6", "testCaseId": "d3c621cc0cbfdae39ff9e65ce7a92d3a", "fullName": "tests.test_a4_Riskcontrolaccount.TestAddRiskControlAccount#test_control_account_a1_error_3", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_a4_Riskcontrolaccount"}, {"name": "subSuite", "value": "TestAddRiskControlAccount"}, {"name": "host", "value": "DESKTOP-U13POE8"}, {"name": "thread", "value": "6480-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_a4_Riskcontrolaccount"}]}